#!/bin/bash

dfx generate

cp -r src/declarations/* ./.harness/actors/dab/interface
pushd ./.harness/actors/dab/interface
    rm **/index.js
    rm **/*.did
    for f in **/*.js; do
        sed -i '' -e '$ d' "$f"
        sed -i '' -e 's/export const idlFactory = ({ IDL }) => {/import { IDL } from \"@dfinity\/candid\";\nexport const idlFactory : IDL.InterfaceFactory = ({ IDL }) => {/g' "$f"
        mv -- "$f" "${f%.js}.ts"
    done
popd
rm -r src/declarations
cp -r ./.harness/actors/dab/interface ./client/src/api/tarot-dab
